%% maxwell_command
% Used to issue either a LAUNCH or TERMINATE command to the control server.

function [status, response] = ...
   maxwell_command(aws_id, aws_key, command, cluster_name, num_nodes, verbosity)

    url = 'https://maxwell-server.lightlabs.co:8000'; % Location of control server.

    % Send the command and receive the response from the control server.
    [status, response] = my_urlread( ...
                    url, 'post', ...
                    {'AWS_ACCESS_KEY_ID', aws_id, ...
                    'AWS_SECRET_ACCESS_KEY', aws_key, ...
                    'command', command, ...
                    'cluster_name', cluster_name, ...
                    'num_nodes', num2str(num_nodes)}, verbosity);

    % If unsuccessful, then print out the response and give an error.
    if ~isempty(regexp(response, 'ERROR')) || ...
        ~isempty(regexp(response, 'unsuccessful'))
        error(sprintf('%s unsuccessful:\n%s', command, response));
    end
end    


